### ISSUE TITLE
Change the group name to JuliaDatabases

### ISSUE THREAD

**Issue by aviks** [JuliaDatabases/Roadmap.jl#3]
Is there any objection to changing the name of of this organisation to JuliaDatabases. We think that describes the org better, and we would like to re-use `JuliaDB` name for a database built *in* Julia. 

cc: @quinnj @iamed2 @tanmaykm @johnmyleswhite as the primary authors of the packages in this org. 

cc: @tkelman

**Comment by quinnj** [comment]
+1 from me.

**Comment by aviks** [comment]
OK, received responses from jacob, eric and tanmay, thanks! Going ahead with this change.

**Comment by quinnj** [comment]
github org name has been changed.
